---
Товары:
  0:
    ID: 17
    Damage: 0
    Цена: 10
    Название: 'Дуб'
  1:
    ID: 17
    Damage: 1
    Цена: 15
    Название: 'Cосна'
  2:
    ID: 17
    Damage: 2
    Цена: 15
    Название: 'Береза'
  3:
    ID: 17
    Damage: 3
    Цена: 15
    Название: 'Пальма'
  4:
    ID: 3
    Damage: 1
    Цена: 100
    Название: 'Земля'
  5:
    ID: 4
    Damage: 1
    Цена: 25
    Название: 'Булыжник'
  6:
    ID: 345
    Damage: 1
    Цена: 1000
    Название: 'Компас'
  7:
    ID: 347
    Damage: 1
    Цена: 1000
    Название: 'Часы'
  8:
    ID: 346
    Damage: 1
    Цена: 2000
    Название: 'Удочка'
  9:
    ID: 261
    Damage: 1
    Цена: 200
    Название: 'Лук'
  10:
    ID: 262
    Damage: 1
    Цена: 3
    Название: 'Стрелы'
  11:
    ID: 354
    Damage: 1
    Цена: 200
    Название: 'Тортик'
  12:
    ID: 297
    Damage: 1
    Цена: 20
    Название: 'Хлебушек'
  13:
    ID: 76
    Damage: 1
    Цена: 50
    Название: 'Кровавый факел'
  14:
    ID: 98
    Damage: 1
    Цена: 20
    Название: 'Каменный кирпич'
  15:
    ID: 20
    Damage: 1
    Цена: 20
    Название: 'Стеклышко'
  16:
    ID: 288
    Damage: 1
    Цена: 10
    Название: 'Перо'
  17:
    ID: 35
    Damage: 0
    Цена: 20
    Название: 'Белая шерсть'
  18:
    ID: 35
    Damage: 1
    Цена: 20
    Название: 'Оранжевая шерсть'
  19:
    ID: 35
    Damage: 2
    Цена: 20
    Название: 'Фиолетовая шерсть'
  20:
    ID: 35
    Damage: 3
    Цена: 20
    Название: 'Аква шерсть'
  21:
    ID: 35
    Damage: 4
    Цена: 20
    Название: 'Желтая шерсть'
  22:
    ID: 35
    Damage: 5
    Цена: 20
    Название: 'Светло-зеленая шерсть'
  23:
    ID: 35
    Damage: 6
    Цена: 20
    Название: 'Розовая шерсть'
  24:
    ID: 35
    Damage: 7
    Цена: 20
    Название: 'Темно-серая шерсть'
  25:
    ID: 35
    Damage: 8
    Цена: 20
    Название: 'Серая шерсть'
  26:
    ID: 35
    Damage: 9
    Цена: 20
    Название: 'Темно-аквамариновая шерсть'
  27:
    ID: 35
    Damage: 10
    Цена: 20
    Название: 'Темно-фиолетовая шерсть'
  28:
    ID: 35
    Damage: 11
    Цена: 20
    Название: 'Синия шерсть'
  29:
    ID: 35
    Damage: 12
    Цена: 20
    Название: 'Коричневая шерсть'
  30:
    ID: 35
    Damage: 13
    Цена: 20
    Название: 'Темно-зеленая шерсть'
  31:
    ID: 35
    Damage: 14
    Цена: 20
    Название: 'Красная шерсть'
  32:
    ID: 35
    Damage: 15
    Цена: 20
    Название: 'Черная шерсть'
  33:
    ID: 450
    Damage: 0
    Цена: 3499
    Название: 'Тотем'
  34:
    ID: 380
    Damage: 0
    Цена: 399
    Название: 'Котел'
  35:
    ID: 379
    Damage: 0
    Цена: 799
    Название: 'Зельеварка'
  36:
    ID: 374
    Damage: 0
    Цена: 24
    Название: 'Колбочка'
  37:
    ID: 375
    Damage: 0
    Цена: 12
    Название: 'Бурдюк'
  38:
    ID: 376
    Damage: 0
    Цена: 12
    Название: 'Глаз'
  39:
    ID: 377
    Damage: 0
    Цена: 14
    Название: 'Пыль'
  40:
    ID: 378
    Damage: 0
    Цена: 14
    Название: 'Магма'
  41:
    ID: 381
    Damage: 0
    Цена: 55
    Название: 'Эко-эндер мира'
  42:
    ID: 382
    Damage: 0
    Цена: 24
    Название: 'Алмазный арбуз'
  43:
    ID: 369
    Damage: 0
    Цена: 85
    Название: 'Палка блейза'
  44:
    ID: 370
    Damage: 0
    Цена: 44
    Название: 'Слеза гаста'
  45:
    ID: 372
    Damage: 0
    Цена: 8
    Название: 'Бородавка'
  46:
    ID: 361
    Damage: 0
    Цена: 35
    Название: 'Семена тыквы'
  47:
    ID: 362
    Damage: 0
    Цена: 44
    Название: 'Семена арбуза'
  48:
    ID: 296
    Damage: 0
    Цена: 75
    Название: 'Семена пшеницы'
  49:
    ID: 338
    Damage: 0
    Цена: 200
    Название: 'Тросник'
  50:
    ID: 287
    Damage: 0
    Цена: 40
    Название: 'Паутинка'
  51:
    ID: 391
    Damage: 0
    Цена: 80
    Название: 'Морковка'
  52:
    ID: 392
    Damage: 0
    Цена: 80
    Название: 'Паутинка'
  53:
    ID: 457
    Damage: 0
    Цена: 4
    Название: 'Редька'
Сообщения:
  Успешно: '§eВаша покупка добавлена в ваш инвентарь!'
  Ошибка: '§cУ вас недостаточно средств на счету для покупки!'
...